// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: ecommerce.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ECommerce_GetProducts_FullMethodName      = "/ECommerce/GetProducts"
	ECommerce_GetSingleProduct_FullMethodName = "/ECommerce/GetSingleProduct"
)

// ECommerceClient is the client API for ECommerce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ECommerceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	GetSingleProduct(ctx context.Context, in *GetSignleProductRequest, opts ...grpc.CallOption) (*GetSingleProductResponse, error)
}

type eCommerceClient struct {
	cc grpc.ClientConnInterface
}

func NewECommerceClient(cc grpc.ClientConnInterface) ECommerceClient {
	return &eCommerceClient{cc}
}

func (c *eCommerceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, ECommerce_GetProducts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCommerceClient) GetSingleProduct(ctx context.Context, in *GetSignleProductRequest, opts ...grpc.CallOption) (*GetSingleProductResponse, error) {
	out := new(GetSingleProductResponse)
	err := c.cc.Invoke(ctx, ECommerce_GetSingleProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ECommerceServer is the server API for ECommerce service.
// All implementations must embed UnimplementedECommerceServer
// for forward compatibility
type ECommerceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	GetSingleProduct(context.Context, *GetSignleProductRequest) (*GetSingleProductResponse, error)
	mustEmbedUnimplementedECommerceServer()
}

// UnimplementedECommerceServer must be embedded to have forward compatible implementations.
type UnimplementedECommerceServer struct {
}

func (UnimplementedECommerceServer) GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedECommerceServer) GetSingleProduct(context.Context, *GetSignleProductRequest) (*GetSingleProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleProduct not implemented")
}
func (UnimplementedECommerceServer) mustEmbedUnimplementedECommerceServer() {}

// UnsafeECommerceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ECommerceServer will
// result in compilation errors.
type UnsafeECommerceServer interface {
	mustEmbedUnimplementedECommerceServer()
}

func RegisterECommerceServer(s grpc.ServiceRegistrar, srv ECommerceServer) {
	s.RegisterService(&ECommerce_ServiceDesc, srv)
}

func _ECommerce_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerce_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECommerce_GetSingleProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignleProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceServer).GetSingleProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerce_GetSingleProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceServer).GetSingleProduct(ctx, req.(*GetSignleProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ECommerce_ServiceDesc is the grpc.ServiceDesc for ECommerce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ECommerce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ECommerce",
	HandlerType: (*ECommerceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ECommerce_GetProducts_Handler,
		},
		{
			MethodName: "GetSingleProduct",
			Handler:    _ECommerce_GetSingleProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecommerce.proto",
}
